#!/usr/bin/env bash
# Publish/update the Homebrew formula for balance in markcipolla/homebrew-tap.
#
# Reads the tarball sha256s from dist/*.sha256 (produced by scripts/build-all.sh),
# renders Formula/balance.rb, and pushes it to the tap.
#
# Env:
#   HOMEBREW_TAP_TOKEN — required. Fine-grained PAT with contents:write on
#                        markcipolla/homebrew-tap.
#   RELEASE_REPO       — owner/name of the repo hosting the release. Defaults
#                        to markcipolla/balance.
#   TAP_REPO           — owner/name of the tap. Defaults to markcipolla/homebrew-tap.
#   TAP_BRANCH         — branch to push to. Defaults to main.
#
# Usage: scripts/update-tap.sh <version>
set -euo pipefail

VERSION="${1:?usage: update-tap.sh <version>}"
RELEASE_REPO="${RELEASE_REPO:-markcipolla/balance}"
TAP_REPO="${TAP_REPO:-markcipolla/homebrew-tap}"
TAP_BRANCH="${TAP_BRANCH:-main}"

: "${HOMEBREW_TAP_TOKEN:?HOMEBREW_TAP_TOKEN not set}"

cd "$(dirname "$0")/.."

read_sha() {
  local asset="$1"
  local file="dist/balance_${VERSION}_${asset}.tar.gz.sha256"
  [ -f "$file" ] || { echo "missing $file" >&2; exit 1; }
  cat "$file"
}

SHA_DARWIN_ARM64="$(read_sha darwin_arm64)"
SHA_DARWIN_AMD64="$(read_sha darwin_amd64)"
SHA_LINUX_ARM64="$(read_sha linux_arm64)"
SHA_LINUX_AMD64="$(read_sha linux_amd64)"

BASE_URL="https://github.com/${RELEASE_REPO}/releases/download/v${VERSION}"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

git clone --depth 1 --branch "$TAP_BRANCH" \
  "https://x-access-token:${HOMEBREW_TAP_TOKEN}@github.com/${TAP_REPO}.git" \
  "$WORK/tap"

mkdir -p "$WORK/tap/Formula"

cat > "$WORK/tap/Formula/balance.rb" <<EOF
# typed: false
# frozen_string_literal: true

# This file is generated by markcipolla/balance's release workflow. DO NOT EDIT.
class Balance < Formula
  desc "Anthropic Messages API proxy that pools Claude subscriptions and API keys"
  homepage "https://github.com/${RELEASE_REPO}"
  version "${VERSION}"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "${BASE_URL}/balance_${VERSION}_darwin_amd64.tar.gz"
      sha256 "${SHA_DARWIN_AMD64}"

      define_method(:install) do
        bin.install "balance"
      end
    end
    if Hardware::CPU.arm?
      url "${BASE_URL}/balance_${VERSION}_darwin_arm64.tar.gz"
      sha256 "${SHA_DARWIN_ARM64}"

      define_method(:install) do
        bin.install "balance"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "${BASE_URL}/balance_${VERSION}_linux_amd64.tar.gz"
      sha256 "${SHA_LINUX_AMD64}"
      define_method(:install) do
        bin.install "balance"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "${BASE_URL}/balance_${VERSION}_linux_arm64.tar.gz"
      sha256 "${SHA_LINUX_ARM64}"
      define_method(:install) do
        bin.install "balance"
      end
    end
  end

  test do
    assert_match "balance ${VERSION}", shell_output("#{bin}/balance --version")
  end
end
EOF

cd "$WORK/tap"
git config user.name "balance-release"
git config user.email "balance-release@users.noreply.github.com"
git add Formula/balance.rb

if git diff --cached --quiet; then
  echo "No formula changes to push."
  exit 0
fi

git commit -m "balance ${VERSION}"
git push origin "$TAP_BRANCH"
echo "Pushed Formula/balance.rb for version ${VERSION} to ${TAP_REPO}."
